version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gcal-daily-notion"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-94fk27rhetc8"
s3_prefix = "gcal-daily-notion"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
